events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:8000;
    }
    upstream user_service {
        server user-service:8000;
    }
    upstream shipment_service {
        server shipment-service:8000;
    }
    upstream iot_service {
        server iot-ingestion-service:8000;
    }
    upstream ml_service {
        server ml-service:8000;
    }

    server {
        listen 80;

        location /api/v1/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/shipments/ {
            proxy_pass http://shipment_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/iot/ {
            proxy_pass http://iot_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
